### ISSUE TITLE
Frontend-Konzeption und Implementation

### ISSUE THREAD

**Issue by ghost** [myossinc/urwalking#1]

**Comment by myossinc** [comment]
Wie wird dem Benutzer die aktuelle Position angezeigt?
(Modifizierte) Google Maps oder eigene Karten?

**Comment by ghost** [comment]
Vielleicht als Frontend nur eine Ausgabe, mit welchem Node das Foto gematched wurde?

**Comment by ghost** [comment]
Zusaetzlicher Button zum Starten der Navigation (Oeffnen der Website)

**Comment by myossinc** [comment]
Bei Match Kamerabild und gematchtes Bild nebeneinander auf dem Screen anzeigen

**Comment by ghost** [comment]
Kamerabild und gematchtes Bild bekommen eigenes issue
